# Generated by Django 4.0.3 on 2022-04-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_note_namenote'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='img',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
